# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rspec", "~> 3.10"

gem "rubocop", "~> 1.25"
gem "rubocop-performance", "~> 1.13"
gem "rubocop-rspec", "~> 2.8"
